import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <p>First write a letter to your customer, then build and design around the letter</p>
      <p>every customer experiences a one on one interaction with your business</p>
      <h1>Capture your amazing life with quality photos is easy!</h1>
      <h3>We bring you an innovative way to reach out to nearby photographers in realtime, or you can make schedule on it. ​ Just one tap, and  photographer is going for you.</h3>
      <h2>"Image of Illustrate products. don't let consumer's imagination take over" </h2>
      <Footer />
    </div>
  );
}
