import Head from "next/head";
import Navbar from "../components/Navbar";
import Intro from "../components/Intro";
import About from "../components/About";
import Footer from "../components/Footer";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Intro />
      <About />
      <Contact />
      <p>First write a letter to your customer, then build and design around the letter</p>
      <p>every customer experiences a one on one interaction with your business</p>

      <Footer />
    </div>
  );
}
